### ISSUE TITLE
1B0Y here!

### ISSUE THREAD

**Issue by 1B0Y** [juanruiz85/project-roleplay#1]
It's a pleasure to see one of my old projects being continued by a fellow developer and I honestly thought no one would really touch this. I'm writing to let you know that due to it being an old project, and that i'm currently in the progress of developing the FTA code from scratch with the original owner DLmass, I'm no longer supporting the gamemode.

Could you please take the notification off the readme?

Thanks!

- Jack (1B0Y)

**Comment by juanruiz85** [comment]
he he he, i have long time that not play in the  FTA SERVER
good luck in your new project

**Comment by VincentOfficial** [comment]
good luck bro
